version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.45.2
  - dependency-name: standard
    versions:
    - 16.0.3
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.2.1
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.4.2
